### ISSUE TITLE
Curved charger line

### ISSUE THREAD

**Issue by snowei19** [ZenkakuHiragana/splatoonsweps#23]
The charger line looks curved when noclipping and in thirdperson. It seems to do this with all playermodels and maps.

**Steps to reproduce:**
1. Load into any map
2. Equip a charger type weapon
3. Go in thirdperson
4. Noclip
5. Charge the weapon

**Screenshot**  
![Screenshot_2022-10-02_18-00-57](https://user-images.githubusercontent.com/48101518/193461044-2bcd18c0-51eb-463d-98b6-c291a0d67630.png)

**Environment**
 - OS: Arch Linux
 - Singleplayer
 - Addon version [2022.10.2](https://github.com/ZenkakuHiragana/splatoonsweps/commit/7bf77fd29d2d441816114ae0560404afb7428c07)

**Comment by ZenkakuHiragana** [comment]
This is intended because third person animation doesn't match player's aim sometimes.  
For example, this also happens when you look at straight up or straight down.

![スクリーンショット 2022-10-03 045032](https://user-images.githubusercontent.com/12111138/193473431-50d6ace8-29df-4ff0-8c56-aa3bcfaeb728.jpg)
