### ISSUE TITLE
Splatoon SWEPS seemingly freezes No Mercy Rooftop

### ISSUE THREAD

**Issue by Munoida** [ZenkakuHiragana/splatoonsweps#49]
**1. Describe the bug**  
This mod, permanently freezes the game whilst trying to load into No Mercy's Final Map on Gmod. Which MAY affect other Left 4 Dead maps.

**2. To Reproduce**  
1. Have this addon installed
2. Open up c8m5_rooftop from Left 4 Dead Category
3. Your game is now frozen (I waited like, 10 minutes before shutting it down lol.)

**3. Expected behavior**  
Supposed to just be able to load up the map as normal with the Splatoon sweps. 

**4. Screenshots or videos**  
The frame it just decides to freeze on.
![618d95eb7a8be70334b38ebcda102700](https://github.com/ZenkakuHiragana/splatoonsweps/assets/84733553/3909d918-17b4-47f1-b708-be90ee82d718)

**5. Environments**
 - Singleplayer
 - Sandbox
 - Downloaded latest as of October 5th, 2023.
 - Latest Windows 10 Version
 - Intel Core i7-3770S CPU @ 3.10GHz
 - NVIDIA GeForce GTX 1050 Ti
 - NVIDIA Driver 537.13
 - 16 GB Ram

**6. Additional context**
All of my enabled addons, excluding Splatoon SWEPS (since it's not an addon downloaded from steam)
![62e51edb8d8e0aa2241f5e3d415675e9](https://github.com/ZenkakuHiragana/splatoonsweps/assets/84733553/e1423686-fcbd-4e4a-8c94-d5a57eb0b987)

**Comment by ZenkakuHiragana** [comment]
Thank you for reporting!  
I found c8m5_rooftop in Left 4 Dead **2** category and confirmed freezing.

CS:GO and L4D2 maps have somewhat different structures compared to other maps so they are likely to have issues on map load.  
Another thought is that static props cause the load time much longer because the addon parses their mesh to generate inkable surfaces for them. I've been addressing this for long time but not much progress are there yet.

I also guess probably it's not freezing but just taking too much time and gradually it finishes loading after a long time like 1 hour.  I have seen it take 30 minutes to finish in my development branch.

**Comment by Munoida** [comment]
Ahhh I see
